image:
    name: ubuntu:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]

stages:
    - test
    - publish

before_script:
    - apt-get update -qy
    - apt-get install -y python3 python3-numpy python3-pip
    - python3 -m pip install pytest
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install drms

run-test:
    stage: test
    script:
        - python3 -m pytest

publish:
    only:
        - tags
    variables:
        TWINE_USERNAME: $TWINE_USERNAME
        TWINE_PASSWORD: $TWINE_PASSWORD
    script:
        - python3 -m pip install twine wheel setuptools
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/*
